description: mnist-keras-functional-single
data:
  base_url: https://s3-us-west-2.amazonaws.com/determined-ai-datasets/mnist/
  training_data: train-images-idx3-ubyte.gz
  training_labels: train-labels-idx1-ubyte.gz
  validation_set_size: 10000
hyperparameters:
  batch_size: 64
  dropout: 0.5
  learning_rate: 1e-3
  layer_size: 100
searcher:
  name: single
  metric: digit_accuracy
  smaller_is_better: False
  max_steps: 5
max_restarts: 0
