description: mnist_pytorch_const_multi_output
data:
  url: https://s3-us-west-2.amazonaws.com/determined-ai-test-data/pytorch_mnist.tar.gz
entrypoints:
  trial_class: model_def_multi_output:MultiMNistTrial
  data_loaders_function: data:make_multi_data_loaders
  download_data_function: data:download_data
hyperparameters:
  learning_rate: 0.001
  dropout: 0.5
  batch_size: 64
  n_filters1: 40
  n_filters2: 40
searcher:
  name: single
  metric: validation_error
  max_steps: 2
  smaller_is_better: true
