description: mnist-estimator-const
hyperparameters:
  learning_rate: 1e-3
  batch_size: 64
  hidden_layer_1: 2500
  hidden_layer_2: 1000
  hidden_layer_3: 500
  dropout: 0.5
searcher:
  name: single
  metric: accuracy
  max_steps: 10
  smaller_is_better: false
