description: cifar_pytorch_const
data:
  url: https://s3-us-west-2.amazonaws.com/determined-ai-datasets/cifar10/cifar-10-python.tar.gz
checkpoint_storage:
  type: s3
  access_key: AKIAJGK24F32WWJ25AEA
  secret_key: 08OM18juqj9p2ivz0kBkxsFVuY/yoC9A0fDHmSeA
  bucket: determined-ai-examples
hyperparameters:
  learning_rate: 1e-4
  learning_rate_decay: 1e-6
  layer1_dropout: 0.25
  layer2_dropout: 0.25
  layer3_dropout: 0.5
  batch_size: 32
searcher:
  name: single
  metric: validation_error
  max_steps: 50
  smaller_is_better: true
